name: Lint and Test

on:
  push:
    branches: [ main ]
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: "Setup uv ${{ matrix.python-version }} / ${{ matrix.os }}"
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        uv sync --group dev
    - name: Lint
      run: |
        uv run ruff check
        # uv run mypy .
    - name: Test
      env:
        # needs to be set, but doesn't need to be valid for running tests
        SAFER_STREETS_DATA_DIR: ""
      run: |
        uv run pytest
     # Build wheel into dist/
    - name: Build wheel
      run: uv build --wheel
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v6
      with:
        name: wheel-dist
        path: dist/*
        if-no-files-found: error
